### ISSUE TITLE
Removal of google analytics from our webapp. 

### ISSUE THREAD

**Issue by joicemjoseph** [netneutrality/netneutrality.in#2]
So it is so bad that you people are using this fu*****\* Gooogle thing. this makes them to get all the list of internet freedom, net neutrality...
Its almost impossible to guess what could be gonna happen in this so ****\* led govt.. 
I smells a possibility of alliance with right hand of big brother and the great dictator.

**Comment by karthikb351** [comment]
Closed till a viable alternative is found
