### ISSUE TITLE
Mail body gets cut when using Google Inbox

### ISSUE THREAD

**Issue by srikanthlogic** [netneutrality/netneutrality.in#21]
Probably a Inbox bug, but mail body gets cut after answer to 11th question because of lengthy mail

Question 11... Further, a recent study[http://dl.acm.org/citation.cfm?id

Mail ends.

**Comment by karthikb351** [comment]
Thanks. Will look into this.

**Comment by sidthekidder** [comment]
There's a limit to the length of the body param, can't see any way to change this -
http://stackoverflow.com/questions/2590467/prefilling-large-volumes-of-body-text-in-gmail-compose-getting-a-request-uri-too

**Comment by karthikb351** [comment]
Oh whoops. Didn't notice this was the wrong repo. Open a ticket at [netneutrality/savetheinternet.in](http://github.com/netneutrality/savetheinternet.in)?

**Comment by jace** [comment]
@sidthekidder that affects desktop email, which is why that workflow is cut and paste. On mobile it's an encoding issue that only affects Google Inbox.
